// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: provider_service.proto

package pers.masteryourself.tutorial.spring.cloud.api;

public interface ProviderServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProviderServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
