// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: provider_service.proto

package pers.masteryourself.tutorial.spring.cloud.api;

public final class ProviderServiceProto {
  private ProviderServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProviderServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProviderServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProviderServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProviderServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026provider_service.proto\")\n\026ProviderServ" +
      "iceRequest\022\017\n\007request\030\001 \001(\t\"+\n\027ProviderS" +
      "erviceResponse\022\020\n\010response\030\001 \001(\t2N\n\017Prov" +
      "iderService\022;\n\004info\022\027.ProviderServiceReq" +
      "uest\032\030.ProviderServiceResponse\"\000BG\n-pers" +
      ".masteryourself.tutorial.spring.cloud.ap" +
      "iB\024ProviderServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProviderServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProviderServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProviderServiceRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_ProviderServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProviderServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProviderServiceResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
