// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: provider_service.proto

package pers.masteryourself.tutorial.spring.cloud.api;

public interface ProviderServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProviderServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
